### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by francescogomez** [lallousx86/rapi#1]
Hi man!

Any help for this project?

**Comment by lallousx86** [comment]
Hi Francesco,

What kind of help you need?

It has been a long time I have not compiled it.

You need the "Libraries/" repo for it to work (if I remember well).

You need to update the VC project to the latest Visual Studio, fix warning and some errors.

**Comment by francescogomez** [comment]
@lallousx86 
I became interested in this project, but what is it for? Does it help to protect programs?

**Comment by lallousx86** [comment]
Hi @francescogomez,

I added a read me file. It answers you.

And no, it does not protect programs.

Thanks
